### ISSUE TITLE
No module named 'model.common'; 'model' is not a package

### ISSUE THREAD

**Issue by HeChengHui** [wcy-cs/KDFSRNet#1]
Got the error when reaching ```common.MeanShfit(...)``` in model.py.  Any way to resolve?

**Comment by wcy-cs** [comment]
Related code is updated in common.py.  Thank you.

**Comment by HeChengHui** [comment]
I got an error for cuda usage. I tried checking by running python on the same terminal and is confirmed to be working. Any possible solution?

`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
`

![image](https://user-images.githubusercontent.com/84503515/193487843-8fa2c615-8812-41e2-a599-cb241d964cf1.png)

**Comment by wcy-cs** [comment]
Sorry, I can't help you to solve this problem. It is a pytorch error. Maybe you can find the solution on the internet.
