### ISSUE TITLE
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)

### ISSUE THREAD

**Issue by GZ-T** [wcy-cs/KDFSRNet#4]
同学你好，在使用你的代码进行测试时，报了标题中提及的错误，具体报错如下：
![微信截图_20230520175218](https://github.com/wcy-cs/KDFSRNet/assets/85470266/b56cd0d4-3f9d-4544-a01c-29bfd16bf18c)
我输出了中间特征发现输入到conv2d中的确实是一个张量，请问这是什么导致的？

**Comment by wcy-cs** [comment]
你好，如果是用预训练的FFHQ_x4, FFHQ_x8 FFHQ_x16，就把from model import net 
student = net.Student(args)  改成 from model import net1 
student = net1.Student(args)

**Comment by GZ-T** [comment]
感谢回答，之前没有注意到pretrained_model路径下的description.txt说明，现在问题以解决。

**Comment by lalagui** [comment]
您好，在运行您的测试代码时，出现了类似上图中提及的错误。我使用的是helen预训练模型，from model import net
student = net.Student(args) 进行测试，请问这个是什么导致的？
![1](https://github.com/wcy-cs/KDFSRNet/assets/108655777/47a6a142-03a5-4992-8284-9c3a113c90b5)

**Comment by wcy-cs** [comment]
您好，helen预训练模型应该使用如果是用预训练的FFHQ_x4, FFHQ_x8 FFHQ_x16，from model import net
student = net.Student(args) ，您看下是不是用了net

**Comment by lalagui** [comment]
感谢回复
