### ISSUE TITLE
测试效果问题

### ISSUE THREAD

**Issue by neverwinHao** [wcy-cs/KDFSRNet#5]
同学您好，我使用您的模型在CelebA-Test数据集上测试的时候得到的效果如下，请问这是正常的吗，感觉并没有恢复多少呢？
低质量图片：
![00000000](https://github.com/wcy-cs/KDFSRNet/assets/106739665/6ebe9063-9b35-49f0-a7ad-bc4c9d276c9f)
恢复之后的图片：
![00000000](https://github.com/wcy-cs/KDFSRNet/assets/106739665/13b05d35-ce82-4948-bf65-a6097cbf7d09)

**Comment by neverwinHao** [comment]
测试过程如下，使用CelebA_x8模型
![image](https://github.com/wcy-cs/KDFSRNet/assets/106739665/11c8f279-cd3e-4b8d-a87d-44c7170af4ff)

**Comment by wcy-cs** [comment]
您好， 我看您的测试过程 好像没看出有什么问题。但是看这两个图片 感觉他俩好像一模一样的，能不能算一下LR和重建结果的psnr看看是不是一样的

**Comment by neverwinHao** [comment]
感谢您的回复！
LR与重建结果的PSNR计算如下：
![image](https://github.com/wcy-cs/KDFSRNet/assets/106739665/219ba69a-5240-4a68-a2ce-5e0c8bd33c17)

同时，我又选取您readme中提到的result文件中的几张图进行测试，结果也不太乐观，向您请教一下是我测试环节哪里出问题，我使用的代码已经上传到仓库：https://github.com/neverwinHao/wcyquestion
例如
![201418](https://github.com/wcy-cs/KDFSRNet/assets/106739665/fee158ba-aa30-46ec-9d11-b0a591ea664b)
重建之后：
![201418](https://github.com/wcy-cs/KDFSRNet/assets/106739665/1fe4dc71-969d-4d9f-aa23-3dee3a32a22c)

期待您的回复！

**Comment by wcy-cs** [comment]
您好，这个201418的低质量图像看起来是有模糊的，可能不太适用于我们当前的模型，我们的模型主要是对bicubic下采样的LR图像重建的。您可以用我们提供的测试集测试一下

**Comment by neverwinHao** [comment]
好的，谢谢！那第一张图片那里为什么从视觉上看不出恢复效果呢？

**Comment by wcy-cs** [comment]
不客气。但是第一个图片没有效果 我感觉也很奇怪。就算不能恢复好，也应该会生成不一样的东西。不好意思  我一时也不太清楚是什么原因。

**Comment by neverwinHao** [comment]
好的，感谢您的回复！
