### ISSUE TITLE
请问训练时计算loss报错

### ISSUE THREAD

**Issue by zhang13359** [wcy-cs/KDFSRNet#6]
HR图像尺寸是256*256，LR图像双三次插值下采样4倍，尺寸是64*64，LR进去网络再出来是64*64，两个图片尺寸不一样，计算loss报错
训练的是教师网络

RuntimeError: The size of tensor a (256) must match the size of tensor b (64) at non-singleton dimension 3

**Comment by wcy-cs** [comment]
你好，需要先将LR插值到和HR一样的大小再送入网络中。
